drop table IF EXISTS items cascade;
drop table IF EXISTS users cascade;
drop table IF EXISTS bookings cascade;
drop table IF EXISTS comments cascade;

create TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT email UNIQUE (email),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

-- items: id, name, description, is_available, owner_id, request_id
create TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR NOT NULL,
  is_available BOOLEAN DEFAULT(false),
  owner_id BIGINT NOT NULL,
  request_id BIGINT NULL,
  CONSTRAINT pk_item PRIMARY KEY (id)
);

alter table items
	add constraint REQUESTS_OWNER_ID_FK
		foreign key (OWNER_ID) references USERS
			on delete cascade;


-- bookings: id, start_date, end_date, item_id, booker_id, status
create TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  start_date TIMESTAMP WITHOUT TIME ZONE,
  end_date TIMESTAMP WITHOUT TIME ZONE,
  item_id BIGINT NOT NULL,
  booker_id BIGINT NOT NULL,
  status varchar(16) NOT NULL,
  CONSTRAINT pk_booking PRIMARY KEY (id)
);

alter table bookings
	add constraint BOOKINGS_ID_FK
		foreign key (BOOKER_ID) references USERS
			on delete cascade;

alter table bookings
	add constraint ITEMS_ID_FK
		foreign key (ITEM_ID) references ITEMS
			on delete cascade;


create TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text VARCHAR NOT NULL,
  item_id BIGINT NOT NULL,
  author_id BIGINT NOT NULL,
  created   TIMESTAMP WITHOUT TIME ZONE,
  CONSTRAINT pk_comment PRIMARY KEY (id)
);


